onboardme_mac.py

fix: updates alfred URL
fix: add a space after cask so that the commands get expanded correctly

fix: update alfred url

---

email_filters/delivery_updates-label_delete.sieve

added new conditional stuff like:
package delivery has been updated
shipment was tendered to FedEx Express
shipment is scheduled

adding more english terminology to delivery updates for emails

---

docs/vim/vim.md

Added instructions to setup touchID as an auth method for sudo. 
Added bottom terminal position commands for vim.

Add vim terminal commands 

---

docs/mac/mac.md

moved to MacOS since its more appropriate than Vim

add touchID for sudo

---

docs/vim/vim.md

bottom isnt a real command, below is.
fix formatting of vim terminal commands

bottom -> below, formatting

---

onboardme/ide_setup.py
setup.py

FINALLY FIXED IT. this was not pleasant to work on, but I am very thankful to the very good docs of packer and the community there in the issues.
This fix is for [Issue #45](https://github.com/jessebot/onboardme/issues/45).

Fix Issue #45: neovim packer install was not returning

---

setup.sh

Adding a check for xcode on Darwin since it has to be re-installed after upgrading from macos 12.X -> 13.0

add xcode check

---

docs/onboardme/getting-started.md
docs/onboardme/installation.md

link was wrong for install page from getting-started page. also added sudo to prereqs for at least linux

Doc fix: fix install instructions

---

onboardme/config/packages.yml
onboardme/pkg_management.py
setup.py

Fixes [#60 ](https://github.com/jessebot/onboardme/issues/60)

Fix snap/flatpak installs

---

docs/python/packaging.md

talk about poetry and little cows

add more python packaging docs

---

docs/onboardme/features.md
docs/onboardme/getting-started.md
onboardme/config/packages.yml
onboardme/help_text.py
pyproject.toml

Also fixing help text and docs to reflect this.

add vlc to snap, as apt vlc is outdated we think

---

onboardme/__init__.py
onboardme/config/onboardme_config.yml
onboardme/console_logging.py
onboardme/ide_setup.py
onboardme/pkg_management.py
onboardme/sudo_setup.py
pyproject.toml

it's not 2fa, its just fa. close enough :)

54 use the built in fingerprint sensor on mac for sudo

---

onboardme/config/packages.yml
onboardme/pkg_management.py
pyproject.toml

Get a load of why it is these weren't installing 🤦

91 brew packages being installed even if they are already installed

---

docs/onboardme/contributing.md

Realized I hadn't put the commands to do the end-to-end build process anywhere. 😩

Adding dockerfile build commands

---

docs/email/neomutt/opening_attachments.md
docs/screen_sharing/rdp.md
onboardme/__init__.py
onboardme/config/packages.yml
onboardme/pkg_management.py
pyproject.toml

This was a number of little fixes rolled into one update, none of them breaking or fixing anything major. Just little feature updates.

quick fix of header text for installs, some devops package updates, and some documentation updates

---

onboardme/config/packages.yaml

libreoffice is a FOSS office suite that replaces Google Docs/Office365
Added a cask install for macos, and apt on linux in the GUI group

add libreoffice

---

docs/cli/git/git.md

doc updates for precommit git hooks

---

onboardme/config/packages.yaml

Closes #149 :) Merge this before #161 so we don't have to generate two tags/releases.

add docker cli; move docker-desktop to devops section; add colima

---

onboardme/config/packages.yaml
pyproject.toml

add cmatrix because it's fun; gitui because it's useful

---

Dockerfile
onboardme/constants.py
poetry.lock
pyproject.toml

adding a Dockerfile and updating mkdir to always create parent directories if they don't exist

Add official beta Dockerfile for all of onboardme; fix initial config directory creation

---

docker/arm_config/devops-onboardme-install.sh
docker/arm_config/music-onboardme-install.sh

we'll just test with somafm for now, and get the rust build container working in CI later

arm docker: remove rust install from music mode; add pyenv; add colors to devops script; fix terrform-docs binary download

---

onboardme/ide_setup.py
poetry.lock
pyproject.toml

this just adds victor mono to the available nerd fonts along with the symbols nerdfonts only and then updates some base dependencies,

add victor mono font, and update some dependencies

---

onboardme/__init__.py
pyproject.toml

publish latest release as something went wrong recently... also takes care of some spacing that was bothering me

try to update onboardme to the latest
